name: drill
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: "2.8.1"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  url_launcher: 6.0.17
  introduction_screen: ^2.1.0
  webview_flutter: ^3.0.0
  lottie: ^1.2.1
  crop_your_image: ^0.6.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
  - assets/
  - assets/images/
